# Generated by Django 4.2.5 on 2023-09-14 18:33

from django.conf import settings
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('main', '0003_category_image_alter_product_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='category',
            name='image',
            field=models.ImageField(upload_to='category_images/'),
        ),
        migrations.CreateModel(
            name='Profile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('phone', models.CharField(help_text='Enter a phone in format +375 (29) XXX-XX-XX', max_length=13, validators=[django.core.validators.RegexValidator(message="Phone number must be in the format: '+375 (29) XXX-XX-XX'", regex='^\\+375 \\(\\d{2}\\) \\d{3}-\\d{2}-\\d{2}$')])),
                ('address', models.CharField(max_length=64)),
                ('icon', models.ImageField(null=True, upload_to='category_images/')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'profile',
                'verbose_name_plural': 'profiles',
            },
        ),
    ]
