# Generated by Django 4.2.5 on 2023-09-15 02:33

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0007_rename_name_supplier_company_name_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='employee',
            name='supplier',
            field=models.ManyToManyField(null=True, to='main.supplier'),
        ),
        migrations.AlterField(
            model_name='supplier',
            name='phone',
            field=models.CharField(default='+375 29 XXXXXXX', max_length=15, validators=[django.core.validators.RegexValidator(message="Phone number must be in the format: '+375 29 XXXXXXX'", regex='^\\+375 \\d{2} \\d{7}$')]),
        ),
    ]
