# Generated by Django 4.2.5 on 2023-09-25 00:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0013_news_alter_profile_birthdate'),
    ]

    operations = [
        migrations.AddField(
            model_name='news',
            name='date',
            field=models.DateField(null=True),
        ),
    ]
