# Generated by Django 4.2.5 on 2023-09-25 01:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0015_news_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='news',
            name='little_content',
            field=models.TextField(null=True),
        ),
    ]
