# Generated by Django 4.2.5 on 2023-09-25 03:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0017_faq'),
    ]

    operations = [
        migrations.CreateModel(
            name='Vacancy',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=155)),
                ('salary', models.PositiveIntegerField()),
                ('discription', models.TextField()),
            ],
        ),
    ]
