# Generated by Django 4.2.5 on 2023-09-25 07:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0020_reviews_new_price'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='reviews',
            name='new_price',
        ),
    ]
