# Generated by Django 4.2.5 on 2023-09-25 07:54

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('main', '0021_remove_reviews_new_price'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Reviews',
            new_name='Sales',
        ),
    ]
