# Generated by Django 4.2.5 on 2023-09-28 23:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0024_feedback_rating'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='profile',
            name='user',
        ),
    ]
