# Generated by Django 4.2.5 on 2023-10-14 21:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0027_category_order'),
    ]

    operations = [
        migrations.AddField(
            model_name='vacancy',
            name='image',
            field=models.ImageField(null=True, upload_to='vacancy_images/'),
        ),
    ]
